language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install sass
- gem install compass
- npm install grunt-cli
services:
- mongodb
deploy:
  provider: openshift
  user: cperry@sapient.com
  password: 1Z24vYx7P!Aji3m
  app: fdaanywhere
  domain: fifteenfifteen
  on:
    repo: sapientgov/openfda-travel
  skip_cleanup: true
branches:
  only:
  - master
