language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install sass
- gem install compass
- npm install grunt-cli
services:
- mongodb
deploy:
  provider: openshift
  user: smagee@sapient.com
  password:
    secure: XmF3knVAJThlhKCF5Cebikssvx087Oe4keYeKKcA69ZB6NMUoFWmIvh+AlBw2H/15eoeCzxSjvzVVZq5xudqriRxLxCNBTs621823OIH1xsMfz6GZkKWLTKgwsqgSwosLKofiEKi6hVI4t4K4PLS/gKvLbx/Yg9ZzGVgUKyEsG1z+YBF8q5CRht9QbMuEi6VBk5mcmYZSMhscNXHiGE/qR95b927se1XtnCrDxnR4OHUSqN94JLhNdjAH7oxVz/g5oh6f4XS350HLr7jOIL6VWwO7qlD2/xM/hNyYor23Onok66G0ViVCVdJNPF9u04mUL+kMKbWSsi9FmHxKzbBzGwNkvWJ1u88msj/bMvrZeQL6EKX1LbyjygIr5x6LpXamM2BbiGtoI/euFIdwvOzv8O93bFk979ktWFM/4V+aiBP9SXsi463QLQS8GlUK8mEguqaHpCZs999x3hisXqrmpp1gV1w7vN2s3RqypuH+UhmZbaRFphO+JsRxFpJDmVtm3/DXPIsbkatlIq5OYhhRW1wUxVW8IAYOXjTsYgmwtQhVMgcKXOJVX9ydxyF1MKGVobueIYzYe7xNJlBt51D8xDCnCs7If5G9HXVhySL87Pb+fajJLDpx/WMYluIm0nwlVD3ycf6aKPqwjszHVp72u9tyqfIWbzN4ltN16xsEpk=
  app: fdaanywhere
  domain: fifteenfifteen
  on:
    repo: sapientgov/openfda-travel
  skip_cleanup: true
  
# whitelist
branches:
  only:
  - master