language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install sass
- gem install compass
- npm install grunt-cli
services:
- mongodb
deploy:
  provider: openshift
  user: cperry@sapient.com
  password: 1Z24vYx7P!Aji3m
  app: fdaanywhere
  domain: fifteenfifteen
  on:
    repo: sapientgov/openfda-travel
  skip_cleanup: true
after_deploy:
- pwd
- pip install requests
- pip install beautifulsoup4
- python misc/wapiti-2.3.0/bin/wapiti http://fdaanywhere-fifteenfifteen.rhcloud.com/#q -o vuln_results_q
- git config --global user.email "umunroe@sapient.com"
- git config --global user.name "Travis-CI"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git commit -a -m 'wapiti vuln results'
- git push
branches:
  only:
  - master
env:
  global:
    secure: Tn2KSEHDcazsNok2ffB3PxzIDc/OqaJScVzvn/OIPl5hhldWpvPPUxBS10cY6rK+ef05Tw7b64D80LCg7lYNtCQn1bNv/6rsLi2dJQP7tHtnwgnAkRVQfAhox2XTjmHj+pWWfUWVdBPsOnfY9PZhhugiaxHAEruTls86BDXr2Psmnpt1n61xC+FSRf2+PnN3Wfd6h2RUdeif1CAVfwdcOvvEZL900yMez1BHmyPEuV7vpii4fd+Q9buvQ9Zqra+qRPYmbZZLfjx5UGVhgflVC0ZXboUNenAzUjLOzO2MxINrQ6vG8/OkmwWJmiY5letpn9FKPxUgrBpFoKLWd1v9VLATXrnt6kr1ic6dYg9TXpNmFcU8KKjyIVAdcEeYcvLQiuDdB+vvTs0czbkoCBPmJvW2oZM4iDyF4vVSWmWN80oO8Kox383++NVOCFURpf8bhSR453abhhXRkssE1nLk0N9n/HxL6Rr3Y4KpstICWbdfdm8MKolWdE7j8HNy0jLgqYu1ItGHjJM6RhM3TyScnT18QMu55EkCm7kLAjepAQN1g2hxNfUG9p9bw54LfEVqCrru88DXNSHr7Rd3X7ry6v3c2EUeWfbZQmA/G8mbudFKXneZhi17phUVmuleQmcAxpX1zxp6vxWb8st/6plHAwZh/8/sdDThI4iB6obKAR4=
